### PR TITLE
Fix Windows not being built as Release

### PR DESCRIPTION
**Pull request by ktwrd**
This PR fixes the `windows` Github Actions Workflow compiling `winter` for Debug (which is selected by default) instead of the build type specified in the matrix.

This was done by modifying the `windows-x64` target that `vcpkg` uses, and forcing the value for `VCPKG_BUILD_TYPE` to be set to whatever the `BUILD_TYPE` value is in the matrix (but lowercase).

(ignore the usage of `VCRUNTIME140D.dll` iun `libcurl-d.dll`, it's not referenced by anything)
```
Microsoft (R) COFF/PE Dumper Version 14.40.33813.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file libcrypto-3-x64.dll

File Type: DLL

  Image has the following dependencies:

    WS2_32.dll
    ADVAPI32.dll
    CRYPT32.dll
    USER32.dll
    KERNEL32.dll
    VCRUNTIME140.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-time-l1-1-0.dll
    api-ms-win-crt-utility-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    api-ms-win-crt-environment-l1-1-0.dll

Dump of file libcurl-d.dll

File Type: DLL

  Image has the following dependencies:

    WS2_32.dll
    zlibd1.dll
    ADVAPI32.dll
    CRYPT32.dll
    bcrypt.dll
    KERNEL32.dll
    VCRUNTIME140D.dll
    ucrtbased.dll

Dump of file libcurl.dll

File Type: DLL

  Image has the following dependencies:

    WS2_32.dll
    bcrypt.dll
    zlib1.dll
    ADVAPI32.dll
    CRYPT32.dll
    KERNEL32.dll
    VCRUNTIME140.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-time-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-utility-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll

Dump of file libssl-3-x64.dll

File Type: DLL

  Image has the following dependencies:

    libcrypto-3-x64.dll
    WS2_32.dll
    KERNEL32.dll
    VCRUNTIME140.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-environment-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-time-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-utility-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll

Dump of file torrent-rasterbar.dll

File Type: DLL

  Image has the following dependencies:

    MSWSOCK.dll
    WS2_32.dll
    IPHLPAPI.DLL
    CRYPT32.dll
    libssl-3-x64.dll
    libcrypto-3-x64.dll
    KERNEL32.dll
    MSVCP140.dll
    VCRUNTIME140.dll
    VCRUNTIME140_1.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-time-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-environment-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll

Dump of file winter-x64-debug.dll

File Type: DLL

  Image has the following dependencies:

    torrent-rasterbar.dll
    WS2_32.dll
    libcrypto-3-x64.dll
    KERNEL32.dll
    ADVAPI32.dll
    MSVCP140.dll
    VCRUNTIME140.dll
    VCRUNTIME140_1.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-environment-l1-1-0.dll
    api-ms-win-crt-locale-l1-1-0.dll
    api-ms-win-crt-time-l1-1-0.dll
    libcurl.dll

Dump of file zlib1.dll

File Type: DLL

  Image has the following dependencies:

    VCRUNTIME140.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    KERNEL32.dll

Dump of file zlibd1.dll

File Type: DLL

  Image has the following dependencies:

    VCRUNTIME140D.dll
    ucrtbased.dll
    KERNEL32.dll

Dump of file adastral.exe

File Type: EXECUTABLE IMAGE
LINK : warning LNK4078: multiple '.text' sections found with different attributes (60000060)
LINK : warning LNK4078: multiple '.idata' sections found with different attributes (C0000040)

  Image has the following dependencies:

    ADVAPI32.dll
    AVRT.dll
    bcrypt.dll
    CRYPT32.dll
    DINPUT8.dll
    dwmapi.dll
    DWrite.dll
    dxgi.dll
    GDI32.dll
    IMM32.dll
    IPHLPAPI.DLL
    KERNEL32.dll
    msvcrt.dll
    ntdll.dll
    ole32.dll
    OLEAUT32.dll
    SHELL32.dll
    USER32.dll
    WINMM.dll
    WS2_32.dll
    WSOCK32.dll
LINK : warning LNK4078: multiple '.rsrc' sections found with different attributes (C0000040)

  Summary

        2000 .00cfg
        1000 .CRT
      1B5000 .bss
       EF000 .data
        1000 .edata
        5000 .idata
        4000 .idata
      18B000 .pdata
      C7B000 .rdata
       6C000 .reloc
        8000 .rsrc
       24000 .rsrc
     35A3000 .text
      92D000 .text
        1000 .tls
      178000 .xdata
        1000 pck

```

### CODE REVIEW

**Comment by int-72h** [comment]
I owe you $10

**Comment by ktwrd** [comment]
> I owe you $10

[sounds good](https://ko-fi.com/ktwrd) :3

**Comment by int-72h** [comment]
sorry i lost it all in the stock crash

**Comment by ktwrd** [comment]
> sorry i lost it all in the stock crash

\:(

**Pull request merged**
