### PR TITLE
Add Advanced Panel

### PR DESCRIPTION
**Pull request by int-72h**
The long, long awaited Advanced Panel.
Should let users move their install directory and set launch arguments.

### CODE REVIEW

**Comment by int-72h** [comment]
Well, it does as a matter of a fact, exist now - however it needs a bit of a facelift + actual rigging up to the back.

**Comment by ktwrd** [comment]
@int-72h could we get some screenshots attached to this PR for this feature? (unable to currently check build since @ work)

**Comment by int-72h** [comment]
it looks pretty terrible currently I will admit; theming's broken on the buttons.

**Comment by int-72h** [comment]
toast3
toast2

**Comment by int-72h** [comment]
The hideous shade is the "clicked" panel theme; it's that garish on purpose to detect theming mistakes.

**Comment by ktwrd** [comment]
> it looks pretty terrible currently I will admit; theming's broken on the buttons.

better than nothing ig. just thinking about doing a blog post for Alpha 4, since there are a lot of changes

**Comment by int-72h** [comment]
I think that the basis is in - main issue is theming now. Once that's sorted it's done.

**Comment by int-72h** [comment]
...I'll sort out the theming later.

**Pull request merged**
